// Generated by scripts/content/build-index.mjs. Do not edit manually.
import article0 from "./published/cach-chon-kich-thuoc-tem-nhan.json";
import article1 from "./published/chuan-bi-file-in-tem-khong-bi-mo.json";
import article2 from "./published/loi-thiet-ke-tem-nhan.json";
import article3 from "./published/tem-chong-nuoc-cho-my-pham-va-do-uong.json";
import article4 from "./published/tem-giay-va-tem-nhua-nen-chon-loai-nao.json";
import article5 from "./published/tem-uv-dtf-la-gi.json";

export const rawBlogArticles = [
  article0,
  article1,
  article2,
  article3,
  article4,
  article5,
] as const;
