import { readdir, writeFile } from "node:fs/promises";

const directory = "content/blog/published";
const files = (await readdir(directory)).filter((file) => file.endsWith(".json")).sort();
const imports = files.map((file, index) => `import article${index} from "./published/${file}";`).join("\n");
const entries = files.map((_, index) => `  article${index},`).join("\n");
const output = `// Generated by scripts/content/build-index.mjs. Do not edit manually.\n${imports}\n\nexport const rawBlogArticles = [\n${entries}\n] as const;\n`;

await writeFile("content/blog/index.ts", output);
console.log(`Indexed ${files.length} published blog articles.`);
