import { mkdir, readdir, writeFile } from "node:fs/promises";

const directory = "content/facebook/published";
await mkdir(directory, { recursive: true });
const files = (await readdir(directory)).filter((file) => file.endsWith(".json")).sort();
const imports = files.map((file, index) => `import post${index} from "./published/${file}";`).join("\n");
const entries = files.map((_, index) => `  post${index},`).join("\n");
const output = `// Generated by scripts/facebook-sync/build-index.mjs. Do not edit manually.\n${imports}${imports ? "\n\n" : ""}export const rawFacebookPosts = [\n${entries}\n] as const;\n`;
await writeFile("content/facebook/index.ts", output, "utf8");
console.log(`Indexed ${files.length} Facebook posts.`);
